kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "nodejs-sample-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: <pipeline content from below>
    type: JenkinsPipeline
  triggers:
    - type: ConfigChange
